---
openapi: 3.0.0
info:
  title: Simple Inventory API
  description: This is a simple API
  contact:
    email: you@your-company.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/joseph97cm/Cine/1.0.0
  description: SwaggerHub API Auto Mocking
paths:
  /login:
    post:
      tags:
      - login
      summary: Autenticación de datos para el ingreso al sistema de administración
      responses:
        "200":
          description: Informacion Correcta
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/administradorExam'
        "400":
          description: BAD REQUEST
          
        "404":
          description: NOT FOUND
          
        "500":
          description: INTERNAL SERVER ERROR
          
  
  /administrators:
    post:
      tags:
      - Administrators
      summary: Agregar los datos para un nuevo administrador
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/administradorPost'
        required: true
      responses:
        "200":
          description: Se ingreso el administrador de forma correcta
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/administradorResultado'
        "400":
          description: BAD REQUEST
          
        "500":
          description: SERVER ERROR
    
    get:
      tags:
      - Administrators
      summary: Mostrar los administradores registrados en el sistema
      description: Devolver el resultado de los administradores (nombre - apellido - fecha_nacimiento - usuario - password - status)
      responses:
        "200":
          description: Successful operation
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/administrador'
            application/json:
              schema:
                $ref: '#/components/schemas/administrador'
        "400":
          description: BAD REQUEST
          
        "404":
          description: NOT FOUND
          
        "500":
          description: INTERNAL SERVER ERROR
    
  /administrators/{id}:
    delete:
      tags:
      - Administrators
      summary: Eliminación logica de administradores
      parameters:
      - name: id
        in: path
        description: ID del administrador
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      responses:
        "200":
           description: Eliminación logica exitosa
          
        "400":
          description: BAD REQUEST
          
        "404":
          description: NOT FOUND
          
        "500":
          description: INTERNAL SERVER ERROR
    put:
      tags:
      - Administrators
      summary: Actualización de datos de un administrador
      parameters:
      - name: id
        in: path
        description: ID del administrador
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/administradorPut'
        required: true
      responses:
        "200":
          description: Se actualizo el administrador de forma correcta
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/administradorActualizado'
        "400":
          description: BAD REQUEST   
        "500":
          description: SERVER ERROR
    get:
      tags:
      - Administrators
      summary: Busqueda de administradores por id
      parameters:
      - name: id
        in: path
        description: ID del administrador
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: Resultado de la busqueda por id
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/administrador'
        "400":
          description: BAD REQUEST   
        "500":
          description: SERVER ERROR
      

components:
  schemas:
    error:
      type: object
      properties:
        errorCode:
          type: integer
          format: int64
        errorMessage:
          type: string
          description: Mensaje del error
        errorDescription:
          type: string
          description: La descripcion en detalle del error
    administrador:
      type: object
      properties:
        id:
          type: integer
          description: Id del administrador
          example: 2
        nombre:
          type: string
          description: Nombre Administrador
          example: Juan Marco
        apellido:
          type: string
          description: Apellido Administrador
          example: Guzman Pozo
        fecha_nacimiento:
          type: string
          description: Fecha de nacimiento
          example: 20/11/1990
        usuario:
          type: string
          description: Nombre de usuario
          example: Marco20
        contraseña:
          type: string
          description: Contraseña del usuario
          example: 12345
        status:
          type: integer
          description: Estado del administrador
          example: 1
    administradorPost:
      type: object
      properties:
        nombre:
          type: string
          description: Nombre Administrador
        apellido:
          type: string
          description: Apellido Administrador
        fecha_nacimiento:
          type: string
          description: Fecha de nacimiento
        usuario:
          type: string
          description: Nombre de usuario
        contraseña:
          type: string
          description: Contraseña del usuario
        status: 
          type: integer
          description: Estado del administrador(0 inactivo, 1 activo)
    administradorExam:
      type: object
      properties:
        usuario:
          type: string
          description: Usuario
          example: Ruben
        contraseña:
          type: string
          description: Contraseña
          example: 12345
    administradorResultado:
      type: object
      properties:
        id: 
          type: integer
          description: id del administrador
          example: 1
        nombre: 
          type: string
          description: Nombre del administrador
          example: Ruben
        apellido: 
          type: string
          description: Apellido del administrador
          example: Diaz
        fecha_nacimiento: 
          type: string
          description: Fecha de nacimiento del administrador
          example: 20/11/1980
        usuario: 
          type: string
          description: Usuario de administrador
          example: rubenpou
        contraseña:
          type: string
          description: Contraseña del administrador
          example: 12345
        status:
          type: integer
          description: Estado del administrador
          example: 1
    administradorPut:
      type: object
      properties:
        nombre:
          type: string
          description: Nombre Administrador
          example: Juan Marco
        apellido:
          type: string
          description: Apellido Administrador
          example: Guzman Pozo
        fecha_nacimiento:
          type: string
          description: Fecha de nacimiento
          example: 20/11/1990
        usuario:
          type: string
          description: Nombre de usuario
          example: Marco20
        contraseña:
          type: string
          description: Contraseña del usuario
          example: 12345
    administradorActualizado:
      type: object
      properties:
        id:
          type: integer
          description: Id del administrador
          example: 2
        nombre:
          type: string
          description: Nombre Administrador
          example: Juan Marco
        apellido:
          type: string
          description: Apellido Administrador
          example: Guzman Pozo
        fecha_nacimiento:
          type: string
          description: Fecha de nacimiento
          example: 20/11/1990
        usuario:
          type: string
          description: Nombre de usuario
          example: Marco48
        contraseña:
          type: string
          description: Contraseña del usuario
          example: bocajuniors1
        status:
          type: integer
          description: Estado del administrador
          example: 1
        
        
        