###
GET http://localhost:8080/administrators/pagina/0
Accept: application/json

###
POST http://localhost:8080/administrators
Content-Type: application/json

{
  "nombre": "Ruben ggg",
  "apellido": "Diaz",
  "fecha_nacimiento": "1999-5-5",
  "usuario": "Ruco",
  "password": "contra"
}

###
PUT http://localhost:8080/administrators/1
Content-Type: application/json

{
  "nombre": "Roberto",
  "apellido": "Melendez",
  "fecha_nacimiento": "1999-5-5",
  "usuario": "Robert",
  "password": "4050"
}

###
DELETE http://localhost:8080/administrators/1


###
PUT http://localhost:8080/administrators/delete/

###
GET http://localhost:8080/administrators/2