### Listado de todos los paises
GET http://localhost:8080/administrators
Accept: application/json

###
PUT http://localhost:8080/administrators
Content-Type: application/json

{
  "nombre": "Cosa",
  "apellido": "Diaz",
  "usuario": "Ruco",
  "password": "Lapoderosa",
  "bot_chat_id": "1",
  "ca": 1
}

###Crear una nueva Direccion
POST http://localhost:8080/administrators
Content-Type: application/json

{
  "nombre": "Ruben",
  "apellido": "Diaz",
  "usuario": "Ruco",
  "password": "Lapoderosa",
  "bot_chat_id": "1"
}

###
DELETE http://localhost:8080/administrators?idAdministrator=1

###
PUT http://localhost:8080/administrators/delete?idAdministrator=2

###
GET http://localhost:8080/administrators/3